# Generated by Django 4.1.2 on 2022-11-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=10)),
                ('materia', models.CharField(max_length=50)),
            ],
        ),
    ]
